project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "slides/"
    - "data/"
 
website:
  google-analytics: G-6LLMGL3T2Q
  title: "BIO4158 course"
  description: "Applied biostatistics with R"
  navbar:
    background: light
    title: "BIO4158: course"
    left:
      - text: Lectures
        href: lectures.qmd
      - text: "Practicals"
        menu:
          - text: "Manual"
            href:  https://biostats-uottawa.github.io/bio4158_manual/
          - text: "Data"
            href: dataset.qmd
          - text: "Extra info"
            href: practical_extra.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: Other resources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Bio4558 (français)
            href: https://biostats-uottawa.github.io/bio4558_cours/
          - text: Bio8940
            href: https://biostats-uottawa.github.io/bio8940_course/
          - text: R-way to hell
            href: https://biostats-uottawa.github.io/intro_r_en.html 
          - text: Chemin de l'enf-R
            href: https://biostats-uottawa.github.io/intro_r_fr.html
    tools:
      - icon: envelope
        href: people.html
        text: Contact
      - icon: github
        menu:
        - text: Code
          href: https://github.com/biostats-uOttawa/bio4158_course
        - text: Issues
          href: https://github.com/Biostats-uOttawa/bio4158_course/issues

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    highlight: kate
    fig_align: center
    css: styles.css
    toc: true

