project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "slides/"
    - "data/"
 
website:
  google-analytics: G-6LLMGL3T2Q
  title: "BIO4158 course"
  description: "Applied biostatistics with R"
  navbar:
    background: light
    title: "BIO4158: course"
    left:
      - text: Lectures
        href: lectures.qmd
      - text: "Practicals"
        menu:
          - text: "Manual"
            href:  https://biostats-uottawa.github.io/bio4158_manual/
          - text: "Data"
            href: dataset.qmd
          - text: "Extra info"
            href: practical_extra.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: Other resources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Biostats avec R (Bio4558)
            href: https://biostats-uottawa.github.io/bio4558_cours/
          - text: Advanced biostats and open science (Bio8940)
            href: https://biostats-uottawa.github.io/bio8940_course/
          - text: R-way to hell (R book)
            href: https://biostats-uottawa.github.io/R/en/
          - text: Chemin de l'enf-R (livre R)
            href: https://biostats-uottawa.github.io/R/fr/
    tools:
      - icon: envelope
        href: people.html
        text: Contact
      - icon: github
        menu:
        - text: Code
          href: https://github.com/biostats-uOttawa/bio4158_course
        - text: Issues
          href: https://github.com/Biostats-uOttawa/bio4158_course/issues

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    highlight: kate
    fig_align: center
    css: css/biostat.css
    toc: true

