---
title: "Lectures"
---

{{< include _links.qmd >}}

```{r}
#| echo: false
#| include: false
knitr::opts_chunk$set(echo = FALSE)
library(lubridate)
library(gt)
library(tidyverse)
source("_yaml_extract.R")
```


### Lecturer {{< fa person-chalkboard >}}

```{r lecturers, results="asis"}
team_df %>%
  filter(role == "lecturer") %>%
  pull(name) %>%
  ui_list()
```

### Teaching assitant`r ifelse(ntutor > 1, 's', '')`
```{r tutors, results="asis"}
team_df %>%
  filter(role == "TA") %>%
  pull(name) %>%
  ui_list()
```
### Office hours {{< fa clock >}}

Meetings will be in-person or online using zoom. Check brightspace for the links.

```{r consult, results="asis"}
team_df %>%
  mutate(consult_print = glue::glue("**{name}**: {consult}")) %>%
  pull(consult_print) %>%
  ui_list()
```

### Schedule {{< fa calendar-days >}}

```{r timetable, results="asis"}
timetable_df %>%
  mutate(timetable = glue::glue("**{class}**: {when} in {where}")) %>%
  pull(timetable) %>%
  ui_list()
```

There are no lectures or tutorials during reading week.

```{r}
check <- character(0)
schedule <- schedule_df %>%
  rowwise() %>%
  mutate(
    day = case_match(
      session,
      1 ~ "mon",
      2 ~ "wed",
      3 ~ "thu"
    ),
    lecture_file = ifelse(
      identical(
        str_subset(
          list.files("slides/", pattern = "html", full.names = TRUE),
          pattern = sprintf("lec-%.2d", week)
        ),
        check
      ),
      NA,
      str_subset(
        list.files("slides/", pattern = "html", full.names = TRUE),
        pattern = sprintf("lec-%.2d", week)
      )
    ),
    lecture = !is.na(lecture_file)
  ) %>%
  ungroup() %>%
  mutate(
    Material = case_when(
      session != 3 & lecture == TRUE ~ glue("<a class='fa fa-link' href='{lecture_file}' target='_blank'></a> <a class='fa fa-file-pdf' href='{sub(\"html\",\"pdf\", lecture_file)}' target='_blank'></a>"),
      session == 3 ~ reading,
      TRUE ~ ""
    ),
    Topic = ifelse(is.na(topic), "", topic),
    Assessment = ifelse(is.na(assessment), "", assessment),
    Practical = ifelse(is.na(practical), "", practical),
    Date = as.Date(
      case_when(
        week > 20 ~ NA,
        day == "wed" & week <= 6 ~ ymd(dat$date_start) + weeks(week),
        day == "wed" & week > 6 ~ ymd(dat$date_start) + weeks(week + 1),
        day == "mon" & week <= 6 ~ ymd(dat$date_start) + weeks(week) - days(2),
        day == "mon" & week > 6 ~ ymd(dat$date_start) + weeks(week + 1) - days(2),
        day == "thu" & week <= 6 ~ ymd(dat$date_start) + weeks(week) + days(1),
        day == "thu" & week > 6 ~ ymd(dat$date_start) + weeks(week + 1) + days(1)
      )
    ),
    wk = ifelse((week %% 2) == 0, "a", ifelse(week < 20, "b", "c"))
  ) %>%
  select(Date, Topic, Material, Practical, Assessment, week, wk)

midsem_break <- 6 # after which week

schedule |>
  gt() |>
  cols_hide(c(week, wk, Practical)) |>
  fmt_markdown(columns = c("Topic", "Material", "Practical", "Assessment")) |>
  fmt_date(
    columns = Date,
    date_style = "MMMd",
    locale = "en"
  ) |>
  data_color(
    columns = wk,
    method = "factor",
    target_columns = everything(),
    palette = c("lightblue", "grey50", "pink")
  ) |>
  #  tab_row_group(
  #    label = "Reading week",
  #    rows = (midsem_break * 2 + 2):26
  #  ) |>
  # row_group_order(groups = c(NA, "Reading week")) |>
  cols_width(
    Date ~ px(50),
    Material ~ px(20)
  ) |>
  sub_missing(missing_text = "") |>
  tab_options(
    table.width = pct(100),
  )
```




