---
title: "Syllabus"
---

{{< include _links.qmd >}}

# Course description

Applied biostatistics to real problems. Experimental design and data collection. Consequences of violating assumptions of different tests. Monte Carlo and Bootstrap analysis. Case studies and exercises in using statistical analysis packages.

# When and where

{{< include where.qmd >}}


# Prerequisite
MAT 2379/2779 or an equivalent introductory statistics course

# Course objectives


   Understand the fundamental principles of statistical inference
   Understand the general principles underlying the most common tests
   Know the assumptions underlying common tests and understand the impact of violating them
   Be able to perform standard statistical analyses using R
   Acquire the capacity to correctly interpret the statistical and biological significance of statistical tests

# Organization
Lectures and class discussions on most common statistical tests; laboratory exercises that illustrate main concepts and allow application of theory to real situations.

# People
## Instructor
Dr. Julien Martin, Department of Biology, GNN 279
Office hours: Monday 14:30 - 16h00 or by appointment: julien.martin@uottawa.ca


## Teaching assistants
Please consult the TA's first for questions related to the lab exercises and assignments.

Alibek Kruglikov: akrug104@uottawa.ca
Office hours: online Monday 8:00-9:00 or by appointment
https://uottawa-ca.zoom.us/j/92008289443?pwd=YXlEcDdwSjltN3poNWI1RG9pa0FEUT09

Mahbubeh Askari Rad: maska102@uottawa.ca
Office hours: GNN 287 (Wednsday 1pm-2pm)







# Texts and software

(recommended but not mandatory) Motulsky, H. J. Intuitive biostatistics. 4th Edition. Oxford University Press, available at the uOttawa bookstore. Used copies of the 4th edition should be around (we used it last year); used copies of the 3rd edition would also be fine.
Errata: See here for corrections to errors in the 2nd, 3rd and 4th edition.
R - a free software environment for statistical computing and graphics. It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS. To download R, please follow this link and then choose your preferred CRAN mirror. 

# Evaluation

Lab assignments: 50%
Midterm (during lab): 20%
Session project: 30%

## Lab assignments
You can work individually or in teams up to three (latter is encouraged). If you submit a team assignment, except under exceptional circumstances all members of the team will receive the same grade. You must submit a single PDF copy of your assignments with all students names and ID listed at the top (submit a single copy for the group). Late assignments will be penalized 10% per day or part thereof. Assignments will consist of either a series of questions to answer or a statistical analysis to perform.



## Exams

### Midterm

in class (see schedule for date), open book, calculators are permitted. A make-up will not be offered. Those with a valid excuse for missing the midterm (e.g., a doctor’s note) will have the final exam re-weighted to be worth 50%. The midterm will be available on the course website afterwards; if you do not write it officially (e.g. for medical reasons), then I strongly suggest you attempt it on your own time. We will happily mark it to provide feedback (your mark won't count toward your final grade). Those who miss the midterm and do not do this generally perform poorly on the final.


### Session project


The final evaluation will take the form of a written report of the analysis of data (unique to each student) of 15 pages and to be submitted before the exam period.


# Marking disputes
If you feel an error has been made in the grading of an assignment or exam, you have 10 working days from the date the item was returned to request a regrading. Beyond 10 working days the mark is considered final. If the issue concerns a lab assignment, please consult the TA that marked it (see above); if it concerns and exam, please see the course instructor.

When a regrading occurs, the new mark will stand whether it is higher or lower, so there is no guarantee your mark will increase. Simple adding mistakes unfortunately happen on occasion given the volume of assignments and exams we have to mark and such cases are easy to correct. However, disputes over partial marks on partially correct answers will not always work out in your favour and should be reserved for situations in which you feel you have a strong case. When requesting a regrading, you must provide an explanation as to what you feel the issue is (i.e. why you think you deserve a higher grade). The more specific this is the better your chance of success.

I do not consider arguments for additional marks simply because you are close to the next letter grade. Sorry.


# Plagiarism

Plagiarism is the act of passing off someone else’s words or ideas as your own. Plagiarism is a major academic offence (see the University of Ottawa regulation on academic fraud: Academic fraud) and is also illegal. We uphold the law. It is critical that you understand what constitutes plagiarism and how you can avoid it. For more information, consult the following document from the Student Academic Success Service.

# Attendance

As per uOttawa policy, to ensure they succeed in all courses of their program of study, students have the responsibility to participate in the various learning and assessment activities for this course. Attendance of the lectures and laboratory are not formally required for this course, although both are STRONGLY recommended. The supplied lecture slides will not include all content presented and discussed in class, and teaching assistants and the professor are available during the labs for help with exercises and assignments. TA and professor office hours are to allow you an opportunity to ask questions related to course material and cannot replace a missed lecture or lab.